import { useMemo, useState } from "react";
import { createFileRoute } from "@tanstack/react-router";
import { Search } from "lucide-react";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { useIncidentLens } from "@/context/incident-lens-context";
import { EmptyState, PageHeader, SeverityBadge, StatusBadge } from "@/components/incidentlens/core";
export const Route=createFileRoute("/history")({head:()=>({meta:[{title:"Incident History — IncidentLens"},{name:"description",content:"Review previous production incidents and their investigation outcomes."},{property:"og:title",content:"Incident History — IncidentLens"},{property:"og:description",content:"Review previous production incidents and their investigation outcomes."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}),component:HistoryPage});
const ALL="all";
function HistoryPage(){const {memories}=useIncidentLens();const [query,setQuery]=useState("");const [severity,setSeverity]=useState(ALL);const [service,setService]=useState(ALL);const [cause,setCause]=useState(ALL);const filtered=useMemo(()=>memories.filter(item=>(!query||`${item.id} ${item.title} ${item.service} ${item.rootCause}`.toLowerCase().includes(query.toLowerCase()))&&(severity===ALL||item.severity===severity)&&(service===ALL||item.service===service)&&(cause===ALL||item.rootCause===cause)),[memories,query,severity,service,cause]);const options=(key:"service"|"rootCause")=>[...new Set(memories.map(item=>item[key]))];return <div className="space-y-6"><PageHeader title="Incident History" subtitle="Previous incidents and their investigation outcomes."/><div className="panel p-4"><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-5"><div className="relative md:col-span-2"><Search className="absolute left-3 top-2.5 size-4 text-muted-foreground"/><Input value={query} onChange={(e)=>setQuery(e.target.value)} className="bg-secondary pl-9" placeholder="Search incidents..."/></div><Filter value={severity} onChange={setSeverity} label="Severity" items={["Critical","High","Medium"]}/><Filter value={service} onChange={setService} label="Service" items={options("service")}/><Filter value={cause} onChange={setCause} label="Root Cause" items={options("rootCause")}/></div></div>{filtered.length?<div className="panel overflow-x-auto"><table className="w-full min-w-[1050px] text-left text-xs"><thead className="border-b border-border bg-secondary/60 text-[10px] uppercase text-muted-foreground"><tr>{["Incident","Service","Severity","Root Cause","Resolution","Outcome","Status","Date"].map(h=><th key={h} className="px-4 py-3 font-semibold">{h}</th>)}</tr></thead><tbody>{filtered.map(item=><tr key={item.id} className="border-b border-border last:border-0 hover:bg-secondary/30"><td className="px-4 py-4"><span className="font-mono font-semibold text-primary">{item.id}</span><span className="mt-1 block font-medium text-foreground">{item.title}</span></td><td className="px-4 py-4 text-muted-foreground">{item.service}</td><td className="px-4 py-4"><SeverityBadge severity={item.severity}/></td><td className="px-4 py-4">{item.rootCause}</td><td className="px-4 py-4 text-muted-foreground">{item.resolution}</td><td className="px-4 py-4 text-muted-foreground">{item.outcome}</td><td className="px-4 py-4"><StatusBadge status={item.status}/></td><td className="px-4 py-4 whitespace-nowrap text-muted-foreground">{item.date}</td></tr>)}</tbody></table></div>:<EmptyState title="No incidents match your filters." description="Try a broader search or reset one of the filters."/>}<p className="text-xs text-muted-foreground">Showing {filtered.length} of {memories.length} resolved incidents</p></div>}
function Filter({value,onChange,label,items}:{value:string;onChange:(value:string)=>void;label:string;items:string[]}){return <Select value={value} onValueChange={onChange}><SelectTrigger className="bg-secondary"><SelectValue placeholder={label}/></SelectTrigger><SelectContent><SelectItem value={ALL}>All {label}</SelectItem>{items.map(item=><SelectItem key={item} value={item}>{item}</SelectItem>)}</SelectContent></Select>}
