from typing import List, Dict, Any

def base_incident(incident: Dict[str, Any]) -> Dict[str, Any]:
    return {
        **incident,
        "timestamp": f"{incident['date']}, 14:30 UTC",
        "reasoning": f"Current symptoms and operational context were compared with prior {incident['service']} incidents.",
        "human_feedback": "Confirmed by incident investigator",
    }

HISTORICAL_INCIDENTS: List[Dict[str, Any]] = [
    base_incident({
        "id": "INC-031",
        "title": "Database Connection Failure",
        "service": "Payment API",
        "severity": "Critical",
        "root_cause": "Database connection leak",
        "context": "Recent deployment",
        "resolution": "Rollback deployment",
        "outcome": "Resolved in 7 minutes",
        "status": "Resolved",
        "date": "Sep 24, 2026",
        "error": "Connection pool exhausted",
    }),
    base_incident({
        "id": "INC-047",
        "title": "API Latency Spike",
        "service": "Checkout API",
        "severity": "High",
        "root_cause": "Traffic spike",
        "context": "3x normal traffic",
        "resolution": "Scale API servers",
        "outcome": "Resolved in 18 minutes",
        "status": "Resolved",
        "date": "Sep 25, 2026",
    }),
    base_incident({
        "id": "INC-052",
        "title": "Database Saturation",
        "service": "Payment API",
        "severity": "Critical",
        "root_cause": "Database connection leak",
        "context": "Recent deployment",
        "resolution": "Rollback deployment",
        "outcome": "Resolved in 11 minutes",
        "status": "Resolved",
        "date": "Sep 26, 2026",
        "error": "Connection pool exhausted",
    }),
    base_incident({
        "id": "INC-062",
        "title": "5xx Error Spike",
        "service": "Order Service",
        "severity": "High",
        "root_cause": "Bad configuration",
        "context": "Configuration change",
        "resolution": "Revert configuration",
        "outcome": "Resolved in 9 minutes",
        "status": "Resolved",
        "date": "Sep 26, 2026",
        "error": "5xx errors",
    }),
    base_incident({
        "id": "INC-071",
        "title": "Memory Exhaustion",
        "service": "User Service",
        "severity": "High",
        "root_cause": "Memory leak",
        "context": "Long service uptime",
        "resolution": "Restart service",
        "outcome": "Resolved in 14 minutes",
        "status": "Resolved",
        "date": "Sep 27, 2026",
        "error": "Memory growth",
    }),
    base_incident({
        "id": "INC-078",
        "title": "API Degradation",
        "service": "Order Service",
        "severity": "Medium",
        "root_cause": "Traffic spike",
        "context": "Marketing campaign caused traffic surge",
        "resolution": "Scale service",
        "outcome": "Resolved in 18 minutes",
        "status": "Resolved",
        "date": "Sep 27, 2026",
    }),
    base_incident({
        "id": "INC-083",
        "title": "Database Connection Failure",
        "service": "Payment API",
        "severity": "Critical",
        "root_cause": "Database connection leak",
        "context": "Recent deployment",
        "resolution": "Rollback deployment",
        "outcome": "Resolved in 8 minutes",
        "status": "Resolved",
        "date": "Sep 28, 2026",
        "error": "Connection pool exhausted",
    }),
    base_incident({
        "id": "INC-091",
        "title": "Payment Errors",
        "service": "Payment API",
        "severity": "High",
        "root_cause": "Configuration regression",
        "context": "Configuration deployment",
        "resolution": "Revert configuration",
        "outcome": "Resolved in 12 minutes",
        "status": "Resolved",
        "date": "Sep 28, 2026",
        "error": "Payment request errors",
    }),
    base_incident({
        "id": "INC-096",
        "title": "High CPU",
        "service": "Search Service",
        "severity": "Medium",
        "root_cause": "Traffic spike",
        "context": "Traffic surge",
        "resolution": "Scale service",
        "outcome": "Resolved in 15 minutes",
        "status": "Resolved",
        "date": "Sep 29, 2026",
        "error": "CPU saturation",
    }),
    base_incident({
        "id": "INC-101",
        "title": "Memory Usage Spike",
        "service": "User Service",
        "severity": "High",
        "root_cause": "Memory leak",
        "context": "New release",
        "resolution": "Rollback",
        "outcome": "Resolved in 10 minutes",
        "status": "Resolved",
        "date": "Sep 29, 2026",
        "error": "Memory usage growth",
    }),
]

ACTIVE_INCIDENT: Dict[str, Any] = base_incident({
    "id": "INC-104",
    "title": "Database Connection Failure",
    "service": "Payment API",
    "severity": "Critical",
    "status": "Active",
    "date": "Sep 29, 2026",
    "started_at": "10:05 AM",
    "duration": "12 minutes",
    "error_rate": "31%",
    "latency": "8.7 sec",
    "db_connections": "94%",
    "cpu": "72%",
    "recent_deployment": "Yes — 12 minutes ago",
    "error": "Connection pool exhausted",
    "root_cause": "Database connection leak",
    "context": "Recent deployment",
    "resolution": "Rollback deployment",
    "outcome": "Pending investigator confirmation",
})

LEARNED_PATTERNS: List[Dict[str, Any]] = [
    {
        "id": "PAT-01",
        "signals": ["Deployment", "DB connections >90%", "Connection pool exhaustion"],
        "result": "Database connection leak",
        "confirmed": 3,
        "successful": 3,
    },
    {
        "id": "PAT-02",
        "signals": ["Traffic spike", "High system load"],
        "result": "Capacity issue",
        "confirmed": 3,
        "successful": 3,
    },
    {
        "id": "PAT-03",
        "signals": ["Configuration change", "5xx errors"],
        "result": "Configuration regression",
        "confirmed": 2,
        "successful": 2,
    },
    {
        "id": "PAT-04",
        "signals": ["Memory growth", "Long uptime / new release"],
        "result": "Memory leak",
        "confirmed": 2,
        "successful": 2,
    },
]

INITIAL_LEARNING_EVENTS: List[str] = [
    "Connection leak diagnosis confirmed",
    "Deployment-related pattern reinforced",
    "Traffic-spike pattern stored",
    "Configuration regression pattern stored",
    "Memory leak pattern stored",
]
