import type { ReactNode } from "react";
import { ArrowDown, Check, CheckCircle2, ChevronRight, CircleAlert, Database, Server, Timer, Zap } from "lucide-react";
import { cn } from "@/lib/utils";
import type { Incident, LearnedPattern, Severity } from "@/types/incident";

export function PageHeader({ title, subtitle, action }: { title:string; subtitle:string; action?:ReactNode }) {
  return <header className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><h1 className="text-2xl font-semibold text-foreground">{title}</h1><p className="mt-1 text-sm text-muted-foreground">{subtitle}</p></div>{action}</header>;
}
export function Eyebrow({ children }: { children:ReactNode }) { return <p className="text-[11px] font-semibold uppercase text-muted-foreground">{children}</p>; }
export function SeverityBadge({ severity }: { severity:Severity }) {
  return <span className={cn("inline-flex items-center rounded border px-2 py-0.5 text-[11px] font-semibold uppercase", severity === "Critical" && "border-critical/30 bg-critical/10 text-critical", severity === "High" && "border-warning/30 bg-warning/10 text-warning", severity === "Medium" && "border-primary/30 bg-primary/10 text-primary")}>{severity}</span>;
}
export function StatusBadge({ status }: { status:string }) { const active=status === "Active"; return <span className={cn("inline-flex items-center gap-1.5 rounded border px-2 py-0.5 text-[11px] font-semibold uppercase", active ? "border-critical/30 bg-critical/10 text-critical" : "border-success/30 bg-success/10 text-success")}><span className={cn("size-1.5 rounded-full", active ? "bg-critical" : "bg-success")} />{status}</span>; }
export function StatCard({ label, value, detail, icon:Icon }: { label:string; value:string|number; detail?:string; icon?:typeof Database }) { return <div className="panel p-4"><div className="flex items-start justify-between"><Eyebrow>{label}</Eyebrow>{Icon && <Icon className="size-4 text-muted-foreground" />}</div><p className="mt-3 text-2xl font-semibold tabular-nums">{value}</p>{detail && <p className="mt-1 text-xs text-muted-foreground">{detail}</p>}</div>; }
export function Metric({ label, value, tone="default" }: { label:string; value:string; tone?:"default"|"critical"|"warning" }) { return <div className="border-l border-border pl-3"><p className="text-[11px] uppercase text-muted-foreground">{label}</p><p className={cn("mt-1 text-lg font-semibold tabular-nums", tone === "critical" && "text-critical", tone === "warning" && "text-warning")}>{value}</p></div>; }
export function IncidentCard({ incident, footer }: { incident:Incident; footer?:ReactNode }) { return <article className="panel overflow-hidden"><div className="flex flex-col gap-4 border-b border-border p-5 sm:flex-row sm:items-start sm:justify-between"><div><div className="flex items-center gap-2"><span className="font-mono text-xs font-semibold text-primary">{incident.id}</span><SeverityBadge severity={incident.severity}/><StatusBadge status={incident.status}/></div><h2 className="mt-3 text-lg font-semibold">{incident.title}</h2><p className="mt-1 text-sm text-muted-foreground">{incident.service}</p></div><div className="flex items-center gap-2 text-xs text-muted-foreground"><Timer className="size-4" /> Started {incident.startedAt}</div></div><div className="grid grid-cols-2 gap-5 p-5 md:grid-cols-5"><Metric label="Error rate" value={incident.errorRate ?? "—"} tone="critical"/><Metric label="API latency" value={incident.latency ?? "—"} tone="warning"/><Metric label="DB connections" value={incident.dbConnections ?? "—"} tone="critical"/><Metric label="CPU" value={incident.cpu ?? "—"}/><Metric label="Deployment" value="12 min ago" tone="warning"/></div>{footer && <div className="flex flex-col gap-3 border-t border-border bg-secondary/35 p-4 sm:flex-row sm:items-center sm:justify-between">{footer}</div>}</article>; }
export function ConfidenceBar({ value }: { value:number }) { return <div><div className="mb-2 flex items-center justify-between text-xs"><span className="text-muted-foreground">Confidence</span><span className="font-mono font-semibold text-primary">{value}%</span></div><div className="h-2 overflow-hidden rounded-sm bg-muted"><div className="h-full rounded-sm bg-primary transition-all duration-700" style={{width:`${value}%`}} /></div></div>; }
export function PatternCard({ pattern, featured=false }: { pattern:LearnedPattern; featured?:boolean }) { return <article className={cn("panel p-5", featured && "border-primary/50 bg-primary/5")}><div className="flex items-start justify-between"><div><Eyebrow>Learned pattern</Eyebrow><p className="mt-2 font-mono text-[11px] text-muted-foreground">{pattern.id}</p></div><Zap className="size-4 text-primary" /></div><div className="mt-5 space-y-2">{pattern.signals.map((signal, index)=><div key={signal} className="flex items-center gap-2 text-sm"><span className="flex size-5 items-center justify-center rounded border border-border bg-secondary font-mono text-[10px] text-muted-foreground">{index+1}</span>{signal}</div>)}<ArrowDown className="ml-1 size-4 text-primary"/><p className="font-semibold text-primary">{pattern.result}</p></div><div className="mt-5 flex gap-5 border-t border-border pt-4 text-xs text-muted-foreground"><span><b className="text-foreground">{pattern.confirmed}</b> confirmed</span><span><b className="text-foreground">{pattern.successful}</b> successful</span></div></article>; }
export function MemoryMatchCard({ incident, similarity, delay=0 }: { incident:Incident; similarity:number; delay?:number }) { return <article className="panel memory-enter p-4" style={{animationDelay:`${delay}ms`}}><div className="flex items-start justify-between"><div><span className="font-mono text-xs font-semibold text-primary">{incident.id}</span><h3 className="mt-1 text-sm font-semibold">{incident.title}</h3></div><div className="text-right"><p className="font-mono text-xl font-semibold text-primary">{similarity}%</p><p className="text-[10px] uppercase text-muted-foreground">similarity</p></div></div><dl className="mt-4 grid gap-3 text-xs"><div><dt className="text-muted-foreground">Root Cause</dt><dd className="mt-0.5 text-foreground">{incident.rootCause}</dd></div><div><dt className="text-muted-foreground">Context</dt><dd className="mt-0.5 text-foreground">{incident.context}</dd></div><div><dt className="text-muted-foreground">Resolution</dt><dd className="mt-0.5 text-foreground">{incident.resolution}</dd></div><div className="flex items-center justify-between border-t border-border pt-3"><span className="text-muted-foreground">{incident.outcome}</span><span className="flex items-center gap-1 text-[10px] font-semibold text-success"><Check className="size-3"/> CONFIRMED</span></div></dl></article>; }
export function EmptyState({ title, description }: { title:string; description:string }) { return <div className="panel flex min-h-48 flex-col items-center justify-center p-8 text-center"><CircleAlert className="size-6 text-muted-foreground"/><h3 className="mt-3 text-sm font-semibold">{title}</h3><p className="mt-1 max-w-sm text-xs text-muted-foreground">{description}</p></div>; }
export function LearningStrip() { const steps=["Current evidence","Hindsight recall","Historical matches","Likely root cause","Human feedback","Memory updated"]; return <div className="overflow-x-auto border-y border-border bg-secondary/30"><div className="mx-auto flex min-w-max max-w-7xl items-center px-5 py-2.5 lg:px-8">{steps.map((step,index)=><div key={step} className="flex items-center"><span className="text-[10px] font-semibold uppercase text-muted-foreground">{step}</span>{index<steps.length-1&&<ChevronRight className="mx-3 size-3 text-border"/>}</div>)}</div></div>; }
export const incidentIcons = { database:Database, server:Server, success:CheckCircle2 };
